### ISSUE TITLE
Disabling pagination returns max: 10 results

### ISSUE THREAD

**Issue by joemsak** [kidpollo/tanker#48]
Given the same search term:

When I use :paginate => false, I get 10 results

when I put the normal pagination options back in (:page => params[:page], :per_page => x) I get 145 results

**Comment by kidpollo** [comment]
can you try using the 'edge' version. I thought I had a fix for this already.

**Comment by kidpollo** [comment]
I just merged some changes from a pull request done by @adrnai which do some changes to the instatiation logic can you please test your code by using the code from master 

gem 'tanker', :git => 'git://github.com/kidpollo/tanker.git'

**Comment by joemsak** [comment]
Trying now, thank you

**Comment by joemsak** [comment]
Hmmm, I still get 10 results for the same search with :paginate => false,
that produces 144 results with :per_page => 5000, :page => params[:page]

**Comment by oleksify** [comment]
Have same issue. Any help?

**Comment by kidpollo** [comment]
I know the problem, the thing is that Index Tank seems to enforce a default of 10

"len": how many results to return (default: 10)

I think I will remove supporting the 'false' option because assuming a number might be counter intuitive. 

Opinions?

**Comment by kidpollo** [comment]
http://indextank.com/documentation/api

Always check the index api for reference :P

**Comment by kidpollo** [comment]
Upgraded the gem to not support the :paginate false
